% Copyright 2013, 2014, 2015, 2016 Thomas M. Mosier, Kendra V. Sharp, and 
% David F. Hill
% This file is part of multiple packages, including the GlobalClimateData 
% Downscaling Package, the Hydropower Potential Assessment Tool, and the 
% Conceptual Cryosphere Hydrology Framework.
% 
% The above named packages are free software: you can 
% redistribute it and/or modify it under the terms of the GNU General 
% Public License as published by the Free Software Foundation, either 
% version 3 of the License, or (at your option) any later version.
% 
% The above named packages are distributed in the hope that it will be 
% useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
% Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with the Downscaling Package.  If not, see 
% <http://www.gnu.org/licenses/>.

function cite = MHS_cite_v2(type)


if regexpbl(type,{'downscale','downscaling'})
    %Displays and outputs text directing users to paper citations and GNU GPL license.
    disp(['The GlobalClimateData.org Downscaling Package implements '...
        'methodologies and codes developed by Thomas M. Mosier, '...
        'David F. Hill, and Kendra V. Sharp.' char(10) ...
        'The scripts and functions associated with this work are ' ...
        'distributed under the GNU General Public License.' char(10) ...
        'When utilizing this work, please use the following citations for ' ...
        'the Downscaling Package and output data:' char(10)]);

    hisCite1 = ['Mosier, T.M., Hill, D.F., & Sharp, K.V. (2014). ' ...
        char(10) '30-Arcsecond monthly climate surfaces with global land coverage. ' ...
        char(10) 'International Journal of Climatology, 34(7), 2175?2188. doi: 10.1002/joc.3829'];
    hisCite2 = ['Mosier, T.M. (2015). Characterizing Linkages '... 
        'between the Climate, ' char(10) 'Cryosphere, and Impacts on Run-of-River '...
        'Hydropower in Data-Sparse Mountain Environments' char(10)  ' (Dissertation).'...
        ' Oregon State University, Corvallis, OR, USA.'];
    proCite1 = ['Mosier, T.M., Hill, D.F., & Sharp, K.V. (2017). ' ...
            'Very High Resolution Climate Projections for Any Land Area: ' char(10) ...
            'Analysis of Empirical Bias Correction Methods in the Context of the Delta Change Method. ' ...
            char(10) 'International Journal of Climatology, doi: 10.1002/joc.5213.'];

    cite = [hisCite1 char(10) char(10) hisCite2 char(10) char(10) proCite1 char(10)];
    
elseif regexpbl(type,{'CCHF','hydro'})
    %Displays and outputs text directing users to paper citations and GNU GPL license.
    disp(['The Conceptual Cryosphere Hydrology (CCHF) Package '...
        'implements methodologies and codes developed by Thomas M. Mosier, '...
        'David F. Hill, and Kendra V. Sharp.' char(10) ...
        'The scripts and functions associated with this work are ' ...
        'distributed under the GNU General Public License.' char(10) ...
        'When utilizing this work, please use the following citations for ' ...
        'the Downscaling Package and output data:' char(10)]);

    cite = ['Mosier, T. M., Hill, D. F., & Sharp, K. V. (2016). How much cryosphere model complexity is just right? ' ...
        char(10) 'Exploration using the conceptual cryosphere hydrology framework. ' char(10) ...
        'The Cryosphere, 10(5), 2147, doi: 10.5194/tc-10-2147-2016' char(10)];
end

disp(cite);

disp(['Please additionally cite all of the input data sources ' ...
    'utilized (e.g. from the Climate Research Unit, '...
    'Willmott & Matsuura, Global Precipitation Climatology Centre, '...
    'WorldClim, and/or the Global Historical Climatology Network).' char(10)]);